[package]
name = "wasm-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-app = {path = "../packages/web-app"}

[dev-dependencies]
wasm-bindgen-test = "0.3.33"

