[package]
name = "serve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-app = {path="../web-app"}

[package.metadata.scripts]
# helper that puts web-app to our dist folder: pkg
publish-web-app = "mkdir -p ../../pkg && rollup ../web-app/index --format iife --file ../../pkg/bundle.js"
build = "wasm-pack build --target web --out-name web-app --release ../web-app && cargo run-script publish-server"
build-dev = "wasm-pack build --target web --out-name web-app --dev ../web-app && cargo run-script publish-server"
dev = "cargo watch -w ../web-app -x 'run-script build-dev'"
# serves the content of pkg/web-app as a server
serve = "cargo run -p server"
serve-watch = "cargo watch -w apps/server -x 'run -p server'"
